import type { Metadata } from "next";
import localFont from "next/font/local";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import "./globals.css";
import { Box, Divider, Stack, SxProps } from "@mui/material";
import Header from "@/src/components/header/header";
import Footer from "@/src/components/footer/footer";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const mainStyle: SxProps = {
        maxWidth: "800px",
        marginRight: "auto",
        marginLeft: "auto",
        p: "0rem 1rem 1rem 1rem",
    };
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Stack direction={"column"} spacing={2} minHeight={"100vh"} justifyContent={"space-between"} sx={mainStyle}>
                    <Stack direction={"column"} spacing={4}>
                        <Box>
                            <Header />
                            <Divider orientation="horizontal" flexItem />
                        </Box>

                        <Box>{children}</Box>
                    </Stack>
                    <Footer />
                </Stack>
            </body>
        </html>
    );
}
